#!/bin/bash

set -e

INDEX=$(curl -s https://nodejs.org/dist/index.json)
LTS=$(echo $INDEX | jq -r 'map(select(.lts))[0].version')
CURRENT=$(node -v)

echo "Installed: $CURRENT"
echo "Current Node.js LTS: $LTS"

if [ $LTS != $CURRENT ]; then
	echo "Updating Node.js to $LTS..."

	PREFIX=$(npm -g prefix || echo "/usr/local")
	case "$(dpkg-architecture -q DEB_TARGET_ARCH)" in
        arm64)
          curl -Lsf "https://nodejs.org/dist/$LTS/node-$LTS-linux-arm64.tar.xz" | \
            sudo tar xJf - -C ${PREFIX} --strip-components=1 --no-same-owner
          ;;
        armhf)
          curl -Lsf "https://unofficial-builds.nodejs.org/download/release/$LTS/node-$LTS-linux-armv6l.tar.gz" | \
            sudo tar xzf - -C ${PREFIX} --strip-components=1 --no-same-owner
          ;;
        esac

	echo "Node.js $(node -v)"
	echo "npm $(npm -v)"

	echo "Node.js updated to $LTS"

	echo "Rebuilding modules..."
	cd "$PREFIX/lib/node_modules"
	sudo npm --unsafe-perm rebuild

	echo "Update Complete"
else
	echo "Node.js is already up-to-date"
fi
