name: Support Request
description: Need help?
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please read the following before you start filling out this form:
        
        * If your issue is specific to a certain plugin, create the issue on that plugin's GitHub project page instead.
        * If your issue is for Homebridge, create the issue on the Homebridge GitHub project page instead.
        * Support via GitHub issues is limited. You may find it more benefitial ask questions on the [Homebridge Discord](https://discord.gg/kqNCe2D) or [Reddit](https://www.reddit.com/r/homebridge/) communities instead.
        * We do not provide support for extra packages, such as PiHole or Deconz, beyond the basic installation scripts.
        * Search through existing issues (resolved or open) which might provide a solution to your problem already.
        * Aim to find a descriptive and precise title for your support request.
  - type: dropdown
    id: raspberry-pi-model
    attributes:
      label: Raspberry Pi Model
      options:
        - Raspberry Pi 1 B
        - Raspberry Pi 2
        - Raspberry Pi 3
        - Raspberry Pi Zero W
        - Raspberry Pi Zero WH
        - Raspberry Pi Zero 2 W
        - Raspberry Pi 3 A+
        - Raspberry Pi 3 B+
        - Raspberry Pi 4 B
        - Other (specify in description)
      description: |
        Please select which Raspberry Pi model you are using.
    validations:
      required: true
  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: |
        Please provide an overview of the current situation and illustrate potential problems or shortcomings.
        
        * What is happening?
        * What you expect to happen?
        * Clear steps explaining how to reproduce the problem.
      placeholder: |
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: text
      description: |
        Please provide the relevant logs showing the error that occurred.

        * Keep this short. Do not paste in hundereds of lines repeating the same error.
        * Show the logs from the service being restarted until the error occurs.
    validations:
      required: false