#!/bin/bash

attempt_counter=0
max_attempts=20
has_pihole=0
until ip route | grep "default"; do
    printf 'Waiting for network...\n'
    if [ ${attempt_counter} -eq ${max_attempts} ];then

       if systemctl is-active --quiet pihole-FTL.service; then
         printf "Stopping Pi-Hole...\n"
         has_pihole=1
         systemctl stop pihole-FTL.service lighttpd.service
         sleep 3
       fi

       printf 'Starting WiFi Connect\n'
       /usr/local/sbin/wifi-connect --portal-ssid="Homebridge WiFi Setup" --activity-timeout=1800
       printf 'WiFi Connection Established...\n'

       if [ ${has_pihole} -eq 1 ]; then
         printf "Starting Pi-Hole...\n"
         systemctl start pihole-FTL.service lighttpd.service
       fi

       exit 0
    fi

    attempt_counter=$(($attempt_counter+1))
    sleep 1
done

printf 'Skipping WiFi Connect\n'
